# Introduction to Numpy 

## NDArray

In [1]:
import numpy as np

In [2]:
data = np.array([10, 11, 12, 13])

In [3]:
print(type(data))  # data is of object type ndarray

<class 'numpy.ndarray'>


## Numpy dimensions

In [4]:
data = np.array([([1, 2]), ([3, 4])])

In [5]:
# print the shape of object "data"
print(data.shape)

(2, 2)


In [6]:
var = np.array(
    [([11, 22, 33, 44, 45, 46]), ([36, 37, 38, 39, 40, 41]), ([61, 62, 63, 64, 65, 66])]
)

In [7]:
# print the shape of object "var"
var.shape

(3, 6)

## Storage List Vs Numpy Array

In [8]:
a = [1, 2, 3, 4]
b = np.array([1, 2, 3, 4])

In [9]:
# Size of the  numpy array
print("Size of Numpy Array ", b.itemsize * b.size, "bytes")

Size of Numpy Array  32 bytes


In [10]:
# Size of the  list
import sys

print("Size of the Python List :", sys.getsizeof(3) * len(a), "bytes")

Size of the Python List : 112 bytes


## Speed List Vs Numpy Array

In [11]:
import time

In [12]:
a1 = range(10000000)
a2 = range(10000000)

In [13]:
b1 = np.arange(10000000)
b2 = np.arange(10000000)

In [14]:
start = time.time()
result = [(x + y) for x, y in zip(a1, a2)]
print((time.time() - start) * 1000, "milliseconds")

974.6520519256592 milliseconds


In [15]:
start = time.time()
output = b1 + b2
print((time.time() - start) * 1000, "milliseconds")

44.63362693786621 milliseconds


## Python Lists

In [16]:
# Declare a list with arbitrary datatypes
# int, string, list and dictionary
a = [1, "Hello", 3.14, [2, 3, 4], {"a": 1, "b": 2}]

In [17]:
# Length of the list
print(len(a))

5


In [18]:
# Acessing the elements using index values
print(a[2])

3.14


## Numpy arrays

In [19]:
# import the numpy module
import numpy as np

In [20]:
# Declare a Numpy array and store it in variable b
b = np.array([1, 2, 3, 4, 5])

In [21]:
# Fetch the length of b (count of total elements in b)
print(len(b))

5


In [22]:
# Find the index value of third  element in the array
# (index starts at 0 (zero))
print(b[2])

3


## Be careful while copying arrays

In [23]:
x = np.array([42, 55, 66])
print("x List:", x)
y = x
print("y List:", y)

x List: [42 55 66]
y List: [42 55 66]


In [24]:
y[0] = 100

In [25]:
print("y List:", y)

y List: [100  55  66]


In [26]:
print("x List:", x)  # now the value of x is  also changed

x List: [100  55  66]


In [27]:
x = np.array([42, 55, 66])
y = x.copy()

In [28]:
y[0] = 100

In [29]:
print("x List:", x)
print("y List:", y)

x List: [42 55 66]
y List: [100  55  66]


##  Mathematical Operation

In [30]:
import numpy as np

In [31]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [32]:
print("Addition :", a + b)

Addition : [ 6  8 10 12]


In [33]:
import numpy as np

a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [34]:
print("Subtraction :", a - b)

Subtraction : [-4 -4 -4 -4]


In [35]:
print("Multiplication :", a * b)

Multiplication : [ 5 12 21 32]


In [36]:
print("Division :", a / b)

Division : [0.2        0.33333333 0.42857143 0.5       ]


## Trigometrial functions

In [37]:
a = [1, 2, 3, 4]

In [38]:
# Sin function
print("Sin values:", np.sin(a))

Sin values: [ 0.84147098  0.90929743  0.14112001 -0.7568025 ]


In [39]:
# Cos function
print("Cos values:", np.cos(a))

Cos values: [ 0.54030231 -0.41614684 -0.9899925  -0.65364362]


## Statistics

In [40]:
data = np.array([1, 23, 52, 3, 6.2, 72, 8, 19, 0, 38, 4, 57, 2, 4])

In [41]:
print(np.mean(data))

20.657142857142855


In [42]:
print(np.median(data))

7.1


In [43]:
print(np.std(data))

23.368773862501527


## Min, Max, Sum

In [44]:
x = np.array([[71, 12, 36], [42, 55, 26]])

In [45]:
print(" Minimum value :", np.min(x))

 Minimum value : 12


In [46]:
print(" Maximum value :", np.max(x))

 Maximum value : 71


In [47]:
print("Addition :", np.sum(x))

Addition : 242


In [48]:
print("Multiplication :", np.product(x))

Multiplication : 1842160320


## Axis  - 0 , 1

In [49]:
x = np.array([[71, 12, 36, 22], [42, 55, 26, 75], [12, 35, 56, 25]])

In [50]:
print(x)

[[71 12 36 22]
 [42 55 26 75]
 [12 35 56 25]]


In [51]:
print(x.shape)

(3, 4)


#### Variable 'x' has 3 rows and 4 columns

In [52]:
print("Column-wise minimum values :", np.min(x, axis=0))

Column-wise minimum values : [12 12 26 22]


In [53]:
print("Column-wise maximum values :", np.max(x, axis=0))

Column-wise maximum values : [71 55 56 75]


In [54]:
print("Row-wise minimum values :", np.min(x, axis=1))

Row-wise minimum values : [12 26 12]


In [55]:
print("Row-wise maximum values :", np.max(x, axis=1))

Row-wise maximum values : [71 75 56]


In [56]:
print("Row-wise sum :", np.sum(x, axis=1))

Row-wise sum : [141 198 128]


In [57]:
print("Column-wise sum :", np.sum(x, axis=0))

Column-wise sum : [125 102 118 122]


## Reshape arrays

In [58]:
x1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

In [59]:
print(x1)

[[1 2 3 4]
 [5 6 7 8]]


In [60]:
# Shape ( 2 rows and 4 columns)
print(x1.shape)

(2, 4)


In [61]:
# Reshape to 4 rows and 2 column
x2 = x1.reshape(4, 2)
print(x2)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [62]:
# Reshape to 8 rows and 1 column
x3 = x1.reshape(8, 1)
print(x3)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


## Vertical stacking

In [63]:
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])
v3 = np.vstack([v1, v2])

In [64]:
print(v3)

[[1 2 3 4]
 [5 6 7 8]]


In [65]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,8])
print(np.vstack([v1,v2]))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 4 and the array at index 1 has size 3

## Horizontal stacking

In [66]:
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])

In [67]:
np.hstack([v1, v2])

array([1, 2, 3, 4, 5, 6, 7, 8])

## Fancy Indexing

In [68]:
import numpy as np

In [69]:
a = np.arange(30).reshape(6, 5)

In [70]:
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


In [71]:
# a[rows, columns]

In [72]:
# displays the second,third and fifth row
# index starting at 0 and all the columns
a_index_2_3_5 = a[[2, 3, 5], :]
print(a_index_2_3_5)

[[10 11 12 13 14]
 [15 16 17 18 19]
 [25 26 27 28 29]]


In [73]:
# displays the elements of 3 and 5 row
# of columns 2 and 5
a_3_5 = a[[3, 5], 2:5]
print(a_3_5)

[[17 18 19]
 [27 28 29]]


## Indexing with  boolean Arrays

In [74]:
data = np.array(
    [[1, 2, 3, 4, 5, 6, 7], [87, 3, 4, 28, 4, 5, 73], [91, 42, 53, 39, 13, 58, 33]],
    dtype="int32",
)

In [75]:
data > 30  # boolean indexing

array([[False, False, False, False, False, False, False],
       [ True, False, False, False, False, False,  True],
       [ True,  True,  True,  True, False,  True,  True]])

In [76]:
# Boolean indexing  with Single condition
data_gt_zero = data[data > 30]
print(data_gt_zero)

[87 73 91 42 53 39 58 33]


In [77]:
# Boolean indexing  with Multiple Conditions
data_gt_30_lt_100 = data[((data > 30) & (data < 100))]
print(data_gt_30_lt_100)

[87 73 91 42 53 39 58 33]


## Broadcasting

In [78]:
import numpy as np

In [79]:
a = np.array([11, 12, 13, 14])
b = np.array([10, 20, 30, 40])

In [80]:
print(a.shape)

(4,)


In [81]:
print(b.shape)

(4,)


In [82]:
c = a * b
print(c)

[110 240 390 560]


### Different shapes

In [83]:
x = np.arange(6).reshape(2, 3)
y = np.array([[1, 2, 3]])

In [84]:
print(x.shape)

(2, 3)


In [85]:
print(y.shape)

(1, 3)


In [86]:
print(x + y)

[[1 3 5]
 [4 6 8]]


###  Different shape conditions not met

In [87]:
a = np.arange(10).reshape(2, 5)
b = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]])

In [88]:
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [89]:
print(b)

[[ 1  2  3  4  5  6  7  8  9 10]]


In [90]:
print(a.shape, b.shape)

(2, 5) (1, 10)


In [91]:
a+b

ValueError: operands could not be broadcast together with shapes (2,5) (1,10) 